### PR TITLE
Review Discussion Forum Turned Off

### PR DESCRIPTION
**Pull request by Luqman-Ud-Din**
**Description:** 

**JIRA:** 
https://edlyio.atlassian.net/browse/EDE-943

**Testing instructions:**

1. Open LMS dashboard
2. Click on a course
3. The discussion tab should not be visible

Screenshot 2020-09-16 at 3 52 19 PM

### CODE REVIEW

**Review by HamzaIbnFarooq — CHANGES_REQUESTED** [review]
I think we should do this through `lms.env.json` configuration file.

**Comment by Luqman-Ud-Din** [comment]
@HamzaIbnFarooq even after setting `ENABLE_DISCUSSION_SERVICE` in `lms.env.json` it will get overridden in `ms/envs/devstack_docker.py`.

That's the reason I have set it here.

**Comment by HamzaIbnFarooq** [comment]
@Luqman-Ud-Din for that purposes we mostly use private.py files in lms and cms.

**Comment by danialmalik** [comment]
@Luqman-Ud-Din if the `lms/envs/devstack_docker.py` file is overriding any value, it will override the config even if its in the common.py. Also `devstack_docker.py` doesn't affect the servers so this shouldn't be an issue. The correct course of action would be applying this setting through the configurations (DevOps team can make the change)

**Comment by Luqman-Ud-Din** [comment]
👍

**Pull request closed without merging**
